name: mr.impression
favicon: null
layout_spectrum: 0.7679710027296096
typography_spectrum: 0.32094399887137115
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7254048124887049
  lightness: 0.10135606047697365
  saturation: 0.5198260124307126
  rhythmicContrast: 0.40353082097135484
purpose: []
